apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-poolcontroller-dashPanel-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nodejs-poolcontroller-dashPanel
    server: nfs-server
