apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-poolcontroller-dashPanel-pv-claim
  labels:
    io.kompose.service: nodejs-poolcontroller-dashPanel-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

