apiVersion: v1
kind: Service
metadata:
  name: poolcontroller-dashpanel
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: poolcontroller-dashpanel-80
    port: 80
    targetPort: 5150
    protocol: TCP
  - name: poolcontroller-dashpanel-5150
    port: 5150
    targetPort: 5150
    protocol: TCP
  selector:
    app: poolcontroller-dashpanel
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245

