apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-backup-pv-claim
  namespace: kube-system
  labels:
    io.kompose.service: etc-backup-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

