kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  selector:
    role: nfs-server
  ports:
    - name: nfs
      port: 2049
      protocol: UDP
    - name: mountd
      port: 20048
      protocol: UDP   
    - name: rpcbind
      port: 111
      protocol: UDP
    - name: nfs-tcp
      port: 2049
      protocol: TCP
    - name: mountd-tcp
      port: 20048
      protocol: TCP
    - name: rpcbind-tcp
      port: 111
      protocol: TCP
