apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nfs-server-alpine-backup-pv-claim
  name: nfs-server-alpine-backup-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
