apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  ports:
  - name: mosquitto-1883
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: mosquitto-9001
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: mosquitto
  type: LoadBalancer
  loadBalancerIP: 192.168.1.253
