apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: traefik
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: traefik
spec:
  ports:
  - name: traefik-8080
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: traefik
  type: LoadBalancer
  loadBalancerIP: 192.168.1.248

