apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: grafana
spec:
  ports:
  - name: grafana-80
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.1.246

