image:
  repository: grafana/grafana
  tag: 6.3.6
plugins: [ grafana-piechart-panel ]
ingress:
  enabled: true
  hosts:
    - grafana
persistence:
  enabled: true
  existingClaim: grafana-pv-claim
  subPath: grafana
grafana.ini:
  auth.basic:
    enabled: true
  auth.anonymous:
    enabled: true

