image:
  repository: grafana/grafana
  tag: 7.4.5
plugins: [ grafana-piechart-panel ]
#ingress:
#  enabled: true
#  hosts:
#    - grafana
service:
  type: LoadBalancer
  localBalancerIP: 192.168.1.246
persistence:
  enabled: true
  existingClaim: grafana-pv-claim
  subPath: grafana
grafana.ini:
  auth.basic:
    enabled: true
  auth.anonymous:
    enabled: true

