apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poolcontroller-logs-pv-claim
  labels:
    io.kompose.service: poolcontroller-logs-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      disk: poolcontroller-logs
