apiVersion: v1
kind: PersistentVolume
metadata:
  name: poolcontroller-data-pv-volume
  labels:
    type: local
    disk: poolcontroller-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /poolcontroller/data
    server: nfs-server
