apiVersion: v1
kind: Service
metadata:
  name: poolcontroller
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: poolcontroller-4200
    port: 4200
    targetPort: 4200
    protocol: TCP
  selector:
    app: poolcontroller
  type: LoadBalancer
  loadBalancerIP: 192.168.1.244

