apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-rpi-pv-claim
  labels:
    io.kompose.service: timemachine-rpi-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  selector:
    matchLabels:
      disk: timemachine-rpi-data

