apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pv-claim
  labels:
    io.kompose.service: home-assistant-config-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
