apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv-volume
  labels:
    type: local
    disk: home-assistant-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home-assistant
    server: nfs-server
