apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-ssl-pv-volume
  labels:
    type: local
    disk: home-assistant-ssl
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /swag/etc/letsencrypt
    server: nfs-server
