apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-dbus-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/dbus"
