apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: home-assistant
spec:
  ports:
  - name: home-assistant-443
    port: 443
    targetPort: 8123
    protocol: TCP
  - name: home-assistant-8123
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: configurator
    port: 3218
    targetPort: 3218
    protocol: TCP
  selector:
    app: home-assistant
  type: LoadBalancer
  loadBalancerIP: 192.168.1.248

