apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
  name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - env:
        - name: value
          value: Europe/London
        - name: variable
          value: TZ
        image: mcblitz/home-assistant:2021.2.1
        #image: mcblitz/home-assistant:2020.12.1
        #image: mcblitz/home-assistant:0.117.5
        #image: mcblitz/home-assistant:0.116.4
        name: home-assistant
        ports:
          - name: api
            containerPort: 8123
            protocol: TCP
          - name: gem
            hostPort: 8000
            containerPort: 8000
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /config
          name: home-assistant-config-pv-claim
        - mountPath: /config/letsencrypt
          name: home-assistant-ssl-pv-claim
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      - name: configurator
        image: 'causticlab/hass-configurator-docker:arm'
        ports:
          - name: configurator
            hostPort: 3218
            containerPort: 3218
            protocol: TCP
        env:
          - name: HC_HASS_API
            value: 'http://127.0.0.1:8123/api/'
          - name: HC_BASEPATH
            value: /config
          - name: HC_ENFORCE_BASEPATH
            value: 'true'
        resources: {}
        volumeMounts:
          - name: home-assistant-config-pv-claim
            mountPath: /config
          - mountPath: /config/letsencrypt
            name: home-assistant-ssl-pv-claim
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
      restartPolicy: Always
      volumes:
      - name: home-assistant-config-pv-claim
        persistentVolumeClaim:
          claimName: home-assistant-config-pv-claim
      - name: home-assistant-ssl-pv-claim
        persistentVolumeClaim:
          claimName: home-assistant-ssl-pv-claim

