apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-pv-claim
  labels:
    io.kompose.service: timemachine-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti

