apiVersion: v1
kind: PersistentVolume
metadata:
  name: timemachine-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/timemachine"
