apiVersion: v1
kind: PersistentVolume
metadata:
  name: gismocaster-var-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /gismocaster/var
    server: nfs-server

