apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gismocaster
  name: gismocaster
spec:
  ports:
  - name: gismocaster-8000
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: gismocaster
  type: LoadBalancer
  loadBalancerIP: 192.168.1.252

