apiVersion: apps/v1
kind: Deployment
metadata:
  name: timemachine-rpi
  labels:
    app: timemachine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timemachine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: timemachine
    spec:
      hostNetwork: true
      containers:
      - image: mcblitz/timemachine-rpi
        name: timemachine
        ports:
        - containerPort: 548
        - containerPort: 636
        resources: {}
        volumeMounts:
        - mountPath: /timemachine
          name: timemachine-rpi-data
        - name: secrets
          mountPath: "/etc/timemachine/secrets"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: timemachine-rpi-data
        persistentVolumeClaim:
          claimName: timemachine-rpi-pv-claim
      - name: secrets
        secret:
          secretName: timemachine-rpi-secrets
      nodeSelector:
        timemachine: mounted
