apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-pv-volume
  labels:
    type: local
    disk: node-red-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /node-red
    server: nfs-server
