apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-red
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-red
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: mcblitz/node-red:1.11.0-1.3.5-12-arm64v8
        name: node-red-homekit
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: node-red-pv-claim
        ports:
          - name: node-red
            containerPort: 1880
            protocol: TCP
      restartPolicy: Always
      volumes:
      - name: node-red-pv-claim
        persistentVolumeClaim:
          claimName: node-red-pv-claim
