apiVersion: v1
kind: Service
metadata:
  name: node-red
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: node-red-80
    port: 80
    targetPort: 1880
    protocol: TCP
  - name: node-red-1880
    port: 1880
    targetPort: 1880
    protocol: TCP
  selector:
    app: node-red
  type: LoadBalancer
  loadBalancerIP: 192.168.1.249

