apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: home-assistant
spec:
  ports:
  - name: letsencrypt
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: letsencrypt
  type: LoadBalancer
  loadBalancerIP: 192.168.1.237

