apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-alpine-backup-pv-volume
  labels:
    type: local
    disk: nfs-server-alpine-backup
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/backup"
