apiVersion: v1
kind: PersistentVolume
metadata:
  name: chronograf-pv-volume
  namespace: tick
  labels:
    type: local
    io.kompose.service: chronograf-pv-claim
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /chronograf
    server: nfs-server
