apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf-pv-claim
  namespace: tick
  labels:
    io.kompose.service: chronograf-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

