apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  namespace: tick
  labels:
    type: local
    io.kompose.service: influxdb-pv-claim
spec:
  storageClassName: manual
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home-automation/influxdb"
