apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegraf-pv-volume
  namespace: tick
  labels:
    type: local
    io.kompose.service: telegraf-pv-claim
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home-automation/telegraf"
