apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegraf-pv-volume
  namespace: tick
  labels:
    type: local
    io.kompose.service: telegraf-pv-claim
    disk: telegraf-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /telegraf
    server: nfs-server
