apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pv-claim
  labels:
    io.kompose.service: letsencrypt-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      disk: letsencrypt-data

