apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-pv-volume
  labels:
    type: local
    disk: letsencrypt-data
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /letsencrypt
    server: nfs-server
