apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blitzhome-certificate
spec:
  commonName: blitzhome.hopto.org
  secretName: blitzhome-certificate-secret
  dnsNames:
  - blitzhome.hopto.org
  - blitzhome.ddns.net
  - home-assistant.blitzhome.ddns.net
  - node-red.blitzhome.ddns.net
  - grafana.blitzhome.ddns.net
  - dashboard.blitzhome.ddns.net
  issuerRef:
    name: issuer-letsencrypt
    kind: ClusterIssuer
  #acme:
  #  config:
  #  - http01:
  #      ingressClass: nginx
  #    domains:
  #    - blitzhome.hopto.org
  #    - blitzhome.ddns.net
  #    - home-assistant.blitzhome.ddns.net
  #    - node-red.blitzhome.ddns.net
  #    - grafana.blitzhome.ddns.net
  #    - dashboard.blitzhome.ddns.net

